from enum import Enum
from pydantic import BaseModel

class ErrorCode(str, Enum):
    INVALID_INPUT = 'INVALID_INPUT'
    PIPELINE_FAILED = 'PIPELINE_FAILED'
    RETRIEVER_NOT_FOUND = 'RETRIEVER_NOT_FOUND'
    RETRIEVAL_FAILED = 'RETRIEVAL_FAILED'
    RULE_CHECK_FAILED = 'RULE_CHECK_FAILED'
    LLM_DISABLED = 'LLM_DISABLED'
    LLM_CALL_FAILED = 'LLM_CALL_FAILED'
    LLM_SCHEMA_INVALID = 'LLM_SCHEMA_INVALID'
    DIFF_FAILED = 'DIFF_FAILED'
    OUTPUT_SCHEMA_INVALID = 'OUTPUT_SCHEMA_INVALID'
    REVIEW_TIMEOUT = 'REVIEW_TIMEOUT'
    RATE_LIMITED = 'RATE_LIMITED'
    LLM_PROVIDER_ERROR = 'LLM_PROVIDER_ERROR'
    INTERNAL_ERROR = 'INTERNAL_ERROR'
    UNKNOWN_ERROR = 'UNKNOWN_ERROR'

class APIError(BaseModel):
    code: ErrorCode
    message: str
    stage: str
    recoverable: bool = True
